### ISSUE TITLE
Update of the SPY lib

### ISSUE THREAD

**Issue by StevenCostiou** [Pharo-XP-Tools/DebuggingSpy#10]
- [x] Ensure that edited code is recorded
- [x] Ensure that copy/paste actions are recorded
- [x] Record do-it and go

**Comment by maxwills** [comment]
I've pushed the recording of copy and paste.  
Now DSSpy instrument the text editor to log copy and paste events.  
There is a setting to enable the recording of the clipboard content (it is disabled by default).  
To enable it, do DSSpy recordClipboardContent: true.  
Note that clipboard copy and paste events are always recorded, and the setting only controls if the contents of the clipboard are included in the record or not.  

The changes create events for any copy or paste operation done on text editors. (via clicking a command, or using keyboard hotkeys). It doesn't logs operations made programmatically (ie, if the user does: Clipboard clipboardText: 'something', it won't be logged. Why? Shortversion: it is simple and effective. Long version: There is a big difficulty about instrumenting the clipboard itself, since there are several clipboards and primitives involved, and the paste operation can't be intercepted at clipboard level (we can intercept a reading of clipboardText, but it could be part of actions different than pasting the clipboard content).

**Comment by maxwills** [comment]
Maybe after all these new records, we need to update the json generated data to include them for the experiment.
